services:
  db:
    image: postgres:16
    container_name: nest-development-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - ./pgdata:/var/lib/postgresql/data
